Rename Subspace to Autonomys
autonomys/subspace-docs pull request #573
Opened 2024-07-30 20:43 UTC by EmilFattakhov

This PR renames the instanced of Subspace Network to Autononys Network while keeping:

- Referenced to Subspace Protocol where makes sense
- Referenced to subspace node and subspace farmer (they weren't renamed just yet)

It also updates the logos to the Autonomy logos.

2024-07-30 21:06 UTC, EmilFattakhov commented
There's a high chance I missed something, but I think most of the instanced have been renamed.

2024-07-31 11:41 UTC, jim-counter requested changes
Mainly small typos.

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/general-information.md
> +For local development and testing, you have multiple options. You can spin up your own version of a Autonomys Developer Node and farmer to deploy contracts, develop applications, and run tests. Alter
```suggestion
For local development and testing, you have multiple options. You can spin up your own version of an Autonomys Developer Node and farmer to deploy contracts, develop applications, and run tests. Alternatively, you can use Ethereum development tools like [Hardhat](https://hardhat.org/hardhat-network/docs/overview) or [Anvil](https://book.getfoundry.sh/anvil/), which are fully compatible with Autonomys due to their EVM compatibility.
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/general-information.md
> +For local development and testing, you have multiple options. You can spin up your own version of a Autonomys Developer Node and farmer to deploy contracts, develop applications, and run tests. Alter
```suggestion
For local development and testing, you have multiple options. You can spin up your own version of an Autonomys Developer Node and farmer to deploy contracts, develop applications, and run tests. Alternatively, you can use Ethereum development tools like [Hardhat](https://hardhat.org/hardhat-network/docs/overview) or [Anvil](https://book.getfoundry.sh/anvil/), which are fully compatible with Autonomys due to their EVM compatibility.
```

2024-07-31 11:41 UTC, jim-counter commented on docs/farming-&-staking/farming/additional-guides/grafana-dashboard.md
> +description: How to configure the Grafana dashboard for a Autonomys Network node
```suggestion
description: How to configure the Grafana dashboard for an Autonomys Network node
```

2024-07-31 11:41 UTC, jim-counter commented on docs/farming-&-staking/farming/advanced-cli/cli-farming-cluster.mdx
> +description: How to run a Autonomys Network Farmer using the farming cluster
```suggestion
description: How to run an Autonomys Network Farmer using the farming cluster
```

2024-07-31 11:41 UTC, jim-counter commented on docs/farming-&-staking/farming/advanced-cli/cli-install.mdx
> +description: How to run a Autonomys Network Farmer with the Substrate CLI
```suggestion
description: How to run an Autonomys Network Farmer with the Substrate CLI
```

2024-07-31 11:41 UTC, jim-counter commented on docs/farming-&-staking/farming/advanced-cli/cli-troubleshooting.mdx
> +description: How to run a Autonomys Network Farmer with the Substrate CLI
```suggestion
description: How to run an Autonomys Network Farmer with the Substrate CLI
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/block_explorer.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/foundry_guide.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/general-information.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/hardhat_guide.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/quick_start.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/remix_guide.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/develop/nova/setting-up-metamask.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on docs/farming-&-staking/farming/advanced-cli/cli-install.mdx
> +1. `Subspace-Node` - This is the executable that actually makes the connection with the Autononys network
```suggestion
1. `Subspace-Node` - This is the executable that actually makes the connection with the Autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/block_explorer.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/foundry_guide.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/general-information.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/hardhat_guide.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/quick_start.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/remix_guide.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 11:41 UTC, jim-counter commented on versioned_docs/version-latest/develop/nova/setting-up-metamask.md
> +  - autononys network
```suggestion
  - autonomys network
```

2024-07-31 12:31 UTC, EmilFattakhov commented
I'm around for a bit @jim-counter if you need help to polish the PR, but looks like you're mostly done here :) Thanks for the review!

2024-08-05 14:31 UTC, EmilFattakhov commented on docs/farming-&-staking/wallets/polkadot.md
> +- You can see your Autonomys Testnet public address via the `...` menu and setting the `Allow Use on Any Chain` dropdown to `Autonomys Testnet`, once you exit you will see the public address now star
Fixed 👍

2024-08-05 14:31 UTC, EmilFattakhov commented on docs/farming-&-staking/wallets/subwallet.md
> +description: How to configure the SubWallet Substrate wallet for the Autonomys Network
Also addressed 👍

2024-08-05 14:34 UTC, EmilFattakhov commented
All comments were addressed @jim-counter, please have another look!

2024-08-05 16:08 UTC, merged