Update SubWallet guide screnshots
autonomys/subspace-docs pull request #764
Opened 2024-11-25 19:49 UTC by EmilFattakhov

Resolves [the issue 763](https://github.com/autonomys/subspace-docs/issues/763)

2024-11-25 21:46 UTC, jim-counter requested changes
Content looks great. A few suggested typo fixes.

There is a section:

> In this example we will be using https://nova-0.gemini-3h.subspace.network/ws

The screenshot does not match the RPC - would be great if we could fix that too.

2024-11-25 21:46 UTC, jim-counter commented on docs/farming-&-staking/wallets/subwallet.md
> +3. In a search bar, start typing the name of the network, e.g. Autonomys.
```suggestion
3. In the search bar, start typing the name of the network, e.g. Autonomys.
```

2024-11-25 21:46 UTC, jim-counter commented on docs/farming-&-staking/wallets/subwallet.md
> +8. Write down your seed phrase in a secure place. You will need it if you ever forget a password, or decide to transfer the account to another PC.
```suggestion
8. Write down your seed phrase in a secure place. You will need it if you ever forget your password, or decide to transfer the account to another PC. 
```

2024-11-25 21:46 UTC, jim-counter commented on docs/farming-&-staking/wallets/subwallet.md
> +9. Congratulations you have fully created your wallet with SubWallet.
```suggestion
9. Congratulations you have successfully created your wallet with SubWallet.
```

2024-11-25 21:46 UTC, jim-counter commented on docs/farming-&-staking/wallets/subwallet.md
> +5. And then click on *Copy* sign to copy the public address.
```suggestion
5. And then click on the *Copy* icon to copy the public address. 
```

2024-11-26 15:00 UTC, EmilFattakhov commented
Thanks @jim-counter, the RPC guide has also been updated 👍

2024-11-26 15:03 UTC, jim-counter approved these changes
Thanks Emil!

2024-11-26 15:07 UTC, merged